name: Repository Integration

on:
  push:
    branches:
      - main  # You can change this to the branch you want to track in Repository B

jobs:
  integrate_repository:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone Repository UAT
        run: |
          git clone https://github.com/IDhanish/UAT.git repository-a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy UAT to Main
        run: |
          # Copy the contents of Repository UAT into Repository Main
          cp -r repository-a .

          # Commit the changes
          git add .
          git commit -m "Integrate Repository UAT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes to Repository Main
        run: |
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
