name: UAT Integration

on:
  push:
    branches:
      - main  # Replace with the branch name you want to trigger the action

jobs:
  integrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: IDhanish/UAT
