name: UAT Integration

on:
  push:
    branches:
      - main  # Replace with the branch name you want to trigger the action

jobs:
  integrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clone UAT Repository
        run: git clone https://github.com/IDhanish/UAT.git uat

      - name: Copy UAT Contents
        run: |
          cp -r uat/* ./  # Copy UAT contents to the current directory

      # You can add further steps here to manage the copied UAT contents.
